services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=ninjabossA3
      - ACCEPT_EULA=Y
    volumes:
      - ./mssql_data:/var/opt/mssql microsoft/mssql-server-linux
    